create table ST_COMMON_TABLE_MASTER(
    ID bigint(20) unsigned NOT NULL PRIMARY KEY COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    CREATE_USER VARCHAR(50) COMMENT '생성자',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    UPDATE_USER VARCHAR(50) COMMENT '수정자',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    TABLE_CODE VARCHAR(50) NOT NULL COMMENT 'TABLE CODE',
    TABLE_NAME VARCHAR(50) NOT NULL COMMENT 'TABLE명',
    TABLE_DESC VARCHAR(100) COMMENT 'TABLE설명'
)COMMENT='TABLE 공용테이블 MASTER' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

create table ST_COMMON_TABLE_COLUMN(
    ID bigint(20) unsigned NOT NULL PRIMARY KEY COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    CREATE_USER VARCHAR(50) COMMENT '생성자',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    UPDATE_USER VARCHAR(50) COMMENT '수정자',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    MASTER_ID bigint(20) unsigned NOT NULL COMMENT 'COMMON MASTER ID',
    COLUMN_CODE VARCHAR(50) NOT NULL COMMENT 'COLUMN CODE',
    COLUMN_COMMENT VARCHAR(50) NOT NULL COMMENT 'COLUMN COMMENT',
    COLUMN_TYPE VARCHAR(50) COMMENT 'COLUMN TYPE',
    INPUT_TYPE VARCHAR(50) COMMENT 'INPUT TYPE',
    COLUMN_SIZE VARCHAR(30) COMMENT 'COLUMN SIZE',
    COLUMN_MAX VARCHAR(30) COMMENT 'COLUMN SIZE MAX',
    COLUMN_PATTERN VARCHAR(50) COMMENT 'COLUMN 패턴',
    COLUMN_ORDER VARCHAR(30) COMMENT 'COLUMN 순서',
    constraint st_common_table_column_st_common_table_master_id_fk
	foreign key (master_id) references st_common_table_master (id)
)COMMENT='TABLE 공용테이블 COLUMN' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

create table ST_COM_DD(
    ID bigint(20) unsigned NOT NULL PRIMARY KEY COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    CREATE_USER VARCHAR(50) COMMENT '생성자',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    UPDATE_USER VARCHAR(50) COMMENT '수정자',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    DD_CODE VARCHAR(50) NOT NULL COMMENT 'DD CODE',
    DD_NAME VARCHAR(50) NOT NULL COMMENT 'DD명',
    DD_DESC VARCHAR(100) COMMENT 'DD설명',
    DD_MODULE VARCHAR(30) COMMENT 'DD 모듈'
)COMMENT='DD MASTER' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

create table ST_COM_DD_VALUE(
    ID bigint(20) unsigned NOT NULL PRIMARY KEY COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    CREATE_USER VARCHAR(50) COMMENT '생성자',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    UPDATE_USER VARCHAR(50) COMMENT '수정자',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    DD_ID bigint(20) unsigned NOT NULL comment 'DD ID',
    DD_VAL VARCHAR(30) NOT NULL COMMENT 'DD VALUE',
    DD_KO VARCHAR(50) COMMENT 'DD LABEL KO',
    DD_EN VARCHAR(50) COMMENT 'DD LABEL EN',
    DD_DEFAULT VARCHAR(1) DEFAULT 'N' COMMENT 'Default 여부',
    USE_YN VARCHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    DD_ORDER bigint(10) COMMENT 'DD 순서',
    DD_FILTER VARCHAR(50) COMMENT 'DD FILTER',
    constraint st_com_dd_value_st_com_dd_id_fk
	foreign key (dd_id) references st_com_dd (id)
)COMMENT='DD VALUE' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

create table ST_BOARD_REPLY
(
    ID bigint(20) unsigned NOT NULL PRIMARY KEY COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    CREATE_USER VARCHAR(50) COMMENT '생성자',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    UPDATE_USER VARCHAR(50) COMMENT '수정자',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    BOARD_ID bigint(20) unsigned NOT NULL comment '게시물 일련번호',
	content text        null comment '댓글내용',
	constraint st_board_reply_st_board_id_fk
	foreign key (board_id) references st_board (id)
)COMMENT='댓글 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


create table st_board(
  ID bigint(20) unsigned NOT NULL PRIMARY KEY COMMENT 'ID',
  CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
  CREATE_USER VARCHAR(50) COMMENT '생성자',
  UPDATE_DATE TIMESTAMP COMMENT '수정일',
  UPDATE_USER VARCHAR(50) COMMENT '수정자',
  DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
  CATEGORY_ID  varchar(20)   comment '게시글 카테고리',
  TITLE    varchar(200)  not null comment '제목',
  content  text          not null comment '게시글',
  TAG      varchar(1000) null comment '태그',
  view_cnt int default 0 not null comment '카운트'
) COMMENT='게시판 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


CREATE TABLE ST_COM_MESSAGE(
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
  CREATE_USER VARCHAR(50) COMMENT '생성자',
  UPDATE_DATE TIMESTAMP COMMENT '수정일',
  UPDATE_USER VARCHAR(50) COMMENT '수정자',
  DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
  MESSAGE_CODE VARCHAR(100) COMMENT '메시지코드',
  LABLE_KO VARCHAR(100) COMMENT '메시지_한글',
  LABLE_EN VARCHAR(100) COMMENT '메시지_영문'
) COMMENT='리소브번들 메시지 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


INSERT INTO seckimdb.st_com_message
(CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER, DELETE_YN, MESSAGE_CODE, LABLE_KO, LABLE_EN)
VALUES ( now(), 'ADMIN', now(), 'ADMIN', 'N', 'LABEL.APPNAME', '강공', 'KANGONG');


DROP TABLE ST_USER_INFO;

CREATE TABLE ST_USER_INFO (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
  CREATE_USER VARCHAR(50) COMMENT '생성자',
  UPDATE_DATE TIMESTAMP COMMENT '수정일',
  UPDATE_USER VARCHAR(50) COMMENT '수정자',
  DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
  USER_ID VARCHAR(50) COMMENT '사용자ID',
  USER_NAME VARCHAR(50) COMMENT '사용자명',
  PASSWORD VARCHAR(50) COMMENT '패스워드',
  AGE INT(3) COMMENT '나이',
  GENDER VARCHAR(10) COMMENT '성별',
  BIRTH_DATE DATE COMMENT '생일',
  CITY VARCHAR(30) COMMENT '도시',
  HOBBY VARCHAR(60) COMMENT '취미',
  COMMENT VARCHAR(300) COMMENT '설명',
  PRIMARY KEY (ID)
) COMMENT='사용자 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

DROP TABLE ST_USER_INFO_ITEM;

CREATE TABLE ST_USER_INFO_ITEM (
  ID BIGINT(20) NOT NULL PRIMARY KEY COMMENT 'ID',
  CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
  CREATE_USER VARCHAR(50) COMMENT '생성자',
  UPDATE_DATE TIMESTAMP COMMENT '수정일',
  UPDATE_USER VARCHAR(50) COMMENT '수정자',
  DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
  USER_INFO_ID BIGINT(20) NOT NULL COMMENT 'USER_INFO ID',
  DISPLAY_ORDER INT(3) COMMENT '순서',
  PROJECT_COMPANY VARCHAR(30) COMMENT '회사',
  PROJECT_NAME VARCHAR(30) COMMENT '프로젝트명',
  PROJECT_YEAR VARCHAR(10) COMMENT '년도',
  APPLY_MODULE VARCHAR(30) COMMENT '적용모듈',
  DESCRIPTION VARCHAR(100) COMMENT '설명'
)  COMMENT='사용자 ITEM 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- INITCAP FUNCTION 생성
DELIMITER $$

DROP FUNCTION IF EXISTS `test`.`initcap`$$

CREATE FUNCTION `initcap`(x char(30)) RETURNS char(30) CHARSET utf8
BEGIN
SET @str='';
SET @l_str='';
WHILE x REGEXP ' ' DO
SELECT SUBSTRING_INDEX(x, ' ', 1) INTO @l_str;
SELECT SUBSTRING(x, LOCATE(' ', x)+1) INTO x;
SELECT CONCAT(@str, ' ', CONCAT(UPPER(SUBSTRING(@l_str,1,1)),LOWER(SUBSTRING(@l_str,2)))) INTO @str;
END WHILE;
RETURN LTRIM(CONCAT(@str, ' ', CONCAT(UPPER(SUBSTRING(x,1,1)),LOWER(SUBSTRING(x,2)))));
END$$

DELIMITER ;


--시퀀스 생성
/* seq_mysql 테이블 생성 */
CREATE TABLE seq_mysql(
id INT NOT NULL,
seq_name VARCHAR(50) NOT NULL
);

/* 생성된 펑션 삭제 */
DROP FUNCTION IF EXISTS get_seq;

/* Auto_increment 적용 */
DELIMITER $$
CREATE FUNCTION get_seq (p_seq_name VARCHAR(45))
RETURNS INT READS SQL DATA
BEGIN
DECLARE RESULT_ID INT;
UPDATE seq_mysql SET id = LAST_INSERT_ID(id+1)
WHERE seq_name = p_seq_name;
SET RESULT_ID = (SELECT LAST_INSERT_ID());
RETURN RESULT_ID;
END $$
DELIMITER ;

/* 시퀀스 생성 */
INSERT INTO seq_mysql
VALUES (0, 'ST_COM_MESSAGE');

/* 시퀀스 삽입 */
get_seq('boardSeq')



